---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.platform.io
  resources:
  - vaultclusterpolicies
  - vaultclusterroles
  - vaultconnections
  - vaultpolicies
  - vaultroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.platform.io
  resources:
  - vaultclusterpolicies/finalizers
  - vaultclusterroles/finalizers
  - vaultconnections/finalizers
  - vaultpolicies/finalizers
  - vaultroles/finalizers
  verbs:
  - update
- apiGroups:
  - vault.platform.io
  resources:
  - vaultclusterpolicies/status
  - vaultclusterroles/status
  - vaultconnections/status
  - vaultpolicies/status
  - vaultroles/status
  verbs:
  - get
  - patch
  - update
