# This rule is not used by the project vault-access-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vault.platform.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-access-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultrole-viewer-role
rules:
- apiGroups:
  - vault.platform.io
  resources:
  - vaultroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.platform.io
  resources:
  - vaultroles/status
  verbs:
  - get
