apiVersion: vault.platform.io/v1alpha1
kind: VaultConnection
metadata:
  labels:
    app.kubernetes.io/name: vault-access-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultconnection-sample
spec:
  # TODO(user): Add fields here
