---
# Manager ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-access-operator.managerRoleName" . }}
  labels:
    {{- include "vault-access-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-access-operator.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-access-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# Metrics Auth ClusterRoleBinding
{{- if and .Values.metrics.enabled .Values.metrics.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-access-operator.metricsAuthRoleName" . }}
  labels:
    {{- include "vault-access-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-access-operator.metricsAuthRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-access-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
