{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "vault-access-operator.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "vault-access-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-access-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vault-access-operator.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
{{- end }}
